apiVersion: v1
kind: Pod
metadata:
  name: my-ubuntu-pod
spec:
  containers:
    - image: ubuntu
      name: my-ubuntu
      command: ["sleep", "infinity"]
      volumeMounts:
        - mountPath: /app
          name: app-volume
  volumes:
    - name: app-volume
      hostPath:
        path:  /home/ubuntu/myhostpath # Replace this with a valid path on your machine
